/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transacciones;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Proyecto DNI
 */
// Interfaz con las clases de transacciones para que usuario pueda escoger
// y la transacción del voto
public class Clases extends javax.swing.JFrame {
    public Inicio usuario;
    /**
     * Creates new form Clases
     */
    public Clases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Notaria = new javax.swing.JButton();
        Registraduria = new javax.swing.JButton();
        Impuestos = new javax.swing.JButton();
        Gobierno = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Voto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Notaria.setText("Notaria");
        Notaria.setMaximumSize(new java.awt.Dimension(130, 30));
        Notaria.setMinimumSize(new java.awt.Dimension(130, 30));
        Notaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotariaActionPerformed(evt);
            }
        });

        Registraduria.setText("Registraduria ");
        Registraduria.setMaximumSize(new java.awt.Dimension(130, 30));
        Registraduria.setMinimumSize(new java.awt.Dimension(130, 30));
        Registraduria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraduriaActionPerformed(evt);
            }
        });

        Impuestos.setText("Impuestos");
        Impuestos.setMaximumSize(new java.awt.Dimension(130, 30));
        Impuestos.setMinimumSize(new java.awt.Dimension(130, 30));
        Impuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpuestosActionPerformed(evt);
            }
        });

        Gobierno.setText("Gobierno");
        Gobierno.setMaximumSize(new java.awt.Dimension(130, 30));
        Gobierno.setMinimumSize(new java.awt.Dimension(130, 30));
        Gobierno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GobiernoActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.setMaximumSize(new java.awt.Dimension(130, 30));
        Salir.setMinimumSize(new java.awt.Dimension(130, 30));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Voto.setText("Voto");
        Voto.setMaximumSize(new java.awt.Dimension(130, 30));
        Voto.setMinimumSize(new java.awt.Dimension(130, 30));
        Voto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Registraduria, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(Impuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Voto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Notaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Gobierno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registraduria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Notaria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Impuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gobierno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Voto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // al oprimir esta opción se abre el menú de transacciones para la notaria
    private void NotariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotariaActionPerformed
        this.setVisible(false);
        usuario.Abrirnot();
    }//GEN-LAST:event_NotariaActionPerformed
    // al oprimir esta opción se abre el menú de transacciones para la registraduría
    private void RegistraduriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraduriaActionPerformed
        this.setVisible(false);
        usuario.Abrirreg();
    }//GEN-LAST:event_RegistraduriaActionPerformed
    // al oprimir esta opcion se abre el menu de transacciones para los impuestos
    private void ImpuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpuestosActionPerformed
        this.setVisible(false);
        usuario.Abririmp();
    }//GEN-LAST:event_ImpuestosActionPerformed
    // al oprimir esta opción se abre el menú de transacciones del gobierno
    private void GobiernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GobiernoActionPerformed
        this.setVisible(false);
        usuario.Abrirgob();
    }//GEN-LAST:event_GobiernoActionPerformed
    // Botón para volver a la interfaz inicial
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        usuario.setVisible(true);
        this.setVisible(false);
        usuario.borrar();
    }//GEN-LAST:event_SalirActionPerformed
    /*Al seleccionar la transacción de voto se toma el día y hora exacta en que 
    se pretende hacer la transacción. Para formar la transacción se escribe en 
    un texto plano el ID, Serial, Clase de transacción (Registraduría), Tipo (Voto)
    y datos de relevancia como es la fecha y hora del voto. Luego de realizar la
    transacción se vuelve a la interfaz de inicio y se reinicia el proceso*/
    private void VotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotoActionPerformed
        String tran;
        DateFormat df = new SimpleDateFormat("d/MM/yyyy/HH:mm:ss");
        Date dia= new Date();
        tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Registraduria Tipo:Voto Datos:"+df.format(dia);
        System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
        JOptionPane.showMessageDialog(this,"Transacción Enviada");
        usuario.setVisible(true);
        this.setVisible(false);
        usuario.borrar();
    }//GEN-LAST:event_VotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gobierno;
    private javax.swing.JButton Impuestos;
    private javax.swing.JButton Notaria;
    private javax.swing.JButton Registraduria;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Voto;
    // End of variables declaration//GEN-END:variables
}
