/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transacciones;

import javax.swing.JOptionPane;

/**
 *
 * @author Proyecto DNI
 */
// Interfaz con el menú de transacciones de la clase Gobierno (Subsidios y SISBEN)
public class Gobierno extends javax.swing.JFrame {
    public Inicio usuario;
    public static int Tipo=0;// En esta variable se indica cual es la transacción a realizar
    /**
     * Creates new form Gobierno
     */
    public Gobierno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inscripcion = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Puntaje = new javax.swing.JTextField();
        Zona = new javax.swing.JComboBox<>();
        Estrato = new javax.swing.JComboBox<>();
        CondicionSocial = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        Subsidio = new javax.swing.JRadioButton();
        TipoSubsidio = new javax.swing.JComboBox<>();
        Volver = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Gobierno");

        Inscripcion.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Inscripcion.setText("Inscripción al SISBEN");
        Inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscripcionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Puntaje Encuesta SISBEN:");
        jLabel1.setEnabled(false);

        Puntaje.setEnabled(false);

        Zona.setMaximumRowCount(4);
        Zona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Zona…", "Principales Ciudades (14)", "Resto Urbano", "Rural" }));
        Zona.setEnabled(false);

        Estrato.setMaximumRowCount(5);
        Estrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estrato:", "0", "1", "2", "3" }));
        Estrato.setEnabled(false);

        CondicionSocial.setMaximumRowCount(5);
        CondicionSocial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Condición Social:", "Desplazado Indígena", "Desplazado por la Violencia", "Pobreza", "Indigencia" }));
        CondicionSocial.setEnabled(false);

        Subsidio.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Subsidio.setText("Solicitud de Subsidios");
        Subsidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubsidioActionPerformed(evt);
            }
        });

        TipoSubsidio.setMaximumRowCount(5);
        TipoSubsidio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar…", "Salud", "Vivienda", "Educación", "Alimentarios" }));
        TipoSubsidio.setEnabled(false);

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.setEnabled(false);
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Subsidio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Inscripcion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Estrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CondicionSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TipoSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Inscripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CondicionSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subsidio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Volver, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Aceptar.getAccessibleContext().setAccessibleName("jButton1");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*al activar este botón se envía la transacción, generando un texto plano con 
    los datos que debe tener una como el ID, Serial del documento. La clase de la 
    transacción como notaria y el tipo de la transacción se verifica si en la 
    variable tipo contiene un uno la transacción es de InscripcióNSISBEN, si 
    contiene un 2 es de subsidio. luego se verifican que se hayan ingresado los datos
    el puntaje, estrato, condición social y zona para las transacciones de inscripción,
    o el tipo de subsidio para el otro tipo de transacción. Esta información 
    ingresada se escribe en el texto plano de la transacción en el campo de Datos:
    Luego se debe enviar el texto plano (se imprime) y se reinician todos los 
    datos de la app para poder realizar una nueva transacción*/
    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        String tran;
        String Lugar;
        String estratificacion;
        String Condicion;
        switch (Tipo) {
            case 1:
                if (Puntaje.getText().length()>0 && Puntaje.getText().matches("[0-9]+")){
                    switch (Zona.getSelectedIndex()){
                        case 1:
                            Lugar="PrincipalesCiudades";
                            break;
                        case 2:
                            Lugar="RestoUrbano";
                            break;
                        case 3:
                            Lugar="Rural";
                            break;
                        default:
                            Lugar="";
                            break;
                    }
                    switch (Estrato.getSelectedIndex()){
                        case 1:
                            estratificacion="Estrato0";
                            break;
                        case 2:
                            estratificacion="Estrato1";
                            break;
                        case 3:
                            estratificacion="Estrato2";
                            break;
                        case 4:
                            estratificacion="Estrato3";
                            break;
                        default:
                            estratificacion="";
                            break;
                    }
                    switch (CondicionSocial.getSelectedIndex()){
                        case 1:
                            Condicion="DesplazadoIndígena";
                            break;
                        case 2:
                            Condicion="DesplazadoViolencia";
                            break;
                        case 3:
                            Condicion="Pobreza";
                            break;
                        case 4:
                            Condicion="Indigencia";
                            break;
                        default:
                            Condicion="";
                            break;
                    }
                    if (Condicion.equals("")||estratificacion.equals("")||Lugar.equals("")){
                        JOptionPane.showMessageDialog(this,"ERROR Seleccionar Zona, Estrato y/o Condición Social");
                    }
                    else{
                        tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Gobierno Tipo:InscripciónSISBEN Datos:"+Puntaje.getText()+"-"+Lugar+"-"+estratificacion+"-"+Condicion;
                        System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                        JOptionPane.showMessageDialog(this,"Transacción Enviada");
                        usuario.setVisible(true);
                        this.setVisible(false);
                        usuario.borrar();
                        start();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"ERROR Ingresar puntuación solo números");
                }
                this.setVisible(false);
                usuario.borrar();
                start();
                break;
            case 2:
                switch (TipoSubsidio.getSelectedIndex()){
                    case 1:
                        tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Gobierno Tipo:Subsidio Datos:Salud";
                        System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                        JOptionPane.showMessageDialog(this,"Transacción Enviada");
                        usuario.setVisible(true);
                        this.setVisible(false);
                        usuario.borrar();
                        start();
                        break;
                    case 2:
                        tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Gobierno Tipo:Subsidio Datos:Vivienda";
                        System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                        JOptionPane.showMessageDialog(this,"Transacción Enviada");
                        usuario.setVisible(true);
                        this.setVisible(false);
                        usuario.borrar();
                        start();
                        break;
                    case 3:
                        tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Gobierno Tipo:Subsidio Datos:Educación";
                        System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                        JOptionPane.showMessageDialog(this,"Transacción Enviada");
                        usuario.setVisible(true);
                        this.setVisible(false);
                        usuario.borrar();
                        start();
                        break;
                    case 4:
                        tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Gobierno Tipo:Subsidio Datos:Alimentarios";
                        System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                        JOptionPane.showMessageDialog(this,"Transacción Enviada");
                        usuario.setVisible(true);
                        this.setVisible(false);
                        usuario.borrar();
                        start();
                        break;
                    default:
                        JOptionPane.showMessageDialog(this,"ERROR seleccionar tipo de subsidio");
                        break;
                }
                break;
            default:
                JOptionPane.showMessageDialog(this,"ERROR Seleccionar Transacción");
                break;
        }
    }//GEN-LAST:event_AceptarActionPerformed
    /*Al seleccionar esta opción se indica que es una transacción de inscripción
    al SISBEN y se habilitan la casilla de texto en la que se 
    ingresa el puntaje del SISBEN, y los menús desplegables de zona, condición 
    social y estrado, además de activar el botón de aceptar y desactivar las
    opciones de subsidios*/
    private void InscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionActionPerformed
        Tipo=1; //el 1 indica que es la transacción de Inscripción al SISBEN
        Subsidio.setSelected(false);
        jLabel1.setEnabled(true);
        Puntaje.setEnabled(true);
        Puntaje.setText("");
        Zona.setEnabled(true);
        Estrato.setEnabled(true);
        CondicionSocial.setEnabled(true);
        TipoSubsidio.setEnabled(false);
        Zona.setSelectedIndex(0);
        Estrato.setSelectedIndex(0);
        CondicionSocial.setSelectedIndex(0);
        TipoSubsidio.setSelectedIndex(0);
        Aceptar.setEnabled(true);
    }//GEN-LAST:event_InscripcionActionPerformed
    /*Al seleccionar esta opción se indica que se realizara una transacción de
    solicitud de subsidios y se habilita el menú desplegable del tipo de subsidio,
    además de activar el botón de aceptar y desactivar las opciones de inscripción al SISBEN*/
    private void SubsidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubsidioActionPerformed
        Tipo=2; //el 2 indica que es la transacción para solicitar un subsidio
        Inscripcion.setSelected(false);
        jLabel1.setEnabled(false);
        Puntaje.setEnabled(false);
        Puntaje.setText("");
        Zona.setEnabled(false);
        Estrato.setEnabled(false);
        CondicionSocial.setEnabled(false);
        TipoSubsidio.setEnabled(true);
        Zona.setSelectedIndex(0);
        Estrato.setSelectedIndex(0);
        CondicionSocial.setSelectedIndex(0);
        TipoSubsidio.setSelectedIndex(0);
        Aceptar.setEnabled(true);
    }//GEN-LAST:event_SubsidioActionPerformed
    // Vuelve al menú de clases de transacciones, reiniciando la interfaz y variables de este menú
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        usuario.Abrirmenu();
        start();
    }//GEN-LAST:event_VolverActionPerformed
    // Función para reiniciar la interfaz y variables de la clase luego de salir del menú de gobierno
    public void start(){
        Tipo=0;
        Inscripcion.setSelected(false);
        Subsidio.setSelected(false);
        jLabel1.setEnabled(false);
        Puntaje.setEnabled(false);
        Puntaje.setText("");
        Zona.setEnabled(false);
        Estrato.setEnabled(false);
        CondicionSocial.setEnabled(false);
        TipoSubsidio.setEnabled(false);
        Zona.setSelectedIndex(0);
        Estrato.setSelectedIndex(0);
        CondicionSocial.setSelectedIndex(0);
        TipoSubsidio.setSelectedIndex(0);
        Aceptar.setEnabled(false);        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gobierno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gobierno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gobierno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gobierno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gobierno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JComboBox<String> CondicionSocial;
    private javax.swing.JComboBox<String> Estrato;
    private javax.swing.JRadioButton Inscripcion;
    private javax.swing.JTextField Puntaje;
    private javax.swing.JRadioButton Subsidio;
    private javax.swing.JComboBox<String> TipoSubsidio;
    private javax.swing.JButton Volver;
    private javax.swing.JComboBox<String> Zona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
