/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transacciones;

import javax.swing.JOptionPane;

/**
 *
 * @author Proyecto DNI
 */
// Interfaz con el menú de transacciones de la clase impuestos
public class Impuestos extends javax.swing.JFrame {
    public Inicio usuario;
    public static String Tipo=""; // En esta variable se indica cual es la transacción a realizar
    /**
     * Creates new form Impuestos
     */
    public Impuestos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Transaccion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JComboBox<>();
        codigo1 = new javax.swing.JComboBox<>();
        codigo2 = new javax.swing.JComboBox<>();
        codigo3 = new javax.swing.JComboBox<>();
        codigo4 = new javax.swing.JComboBox<>();
        codigo5 = new javax.swing.JComboBox<>();
        codigo6 = new javax.swing.JComboBox<>();
        codigo7 = new javax.swing.JComboBox<>();
        codigo8 = new javax.swing.JComboBox<>();
        codigo9 = new javax.swing.JComboBox<>();
        codigo10 = new javax.swing.JComboBox<>();
        codigo13 = new javax.swing.JComboBox<>();
        codigo16 = new javax.swing.JComboBox<>();
        codigo11 = new javax.swing.JComboBox<>();
        codigo14 = new javax.swing.JComboBox<>();
        codigo17 = new javax.swing.JComboBox<>();
        codigo12 = new javax.swing.JComboBox<>();
        codigo15 = new javax.swing.JComboBox<>();
        codigo18 = new javax.swing.JComboBox<>();
        Volver = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Impuestos");

        Transaccion.setFont(new java.awt.Font("Tahoma", 1, 29)); // NOI18N
        Transaccion.setMaximumRowCount(3);
        Transaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Transacción:", "Inscripción al RUT", "Cambios en el RUT" }));
        Transaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaccionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Responsabilidades:");
        jLabel1.setToolTipText("");
        jLabel1.setEnabled(false);

        Cantidad.setMaximumRowCount(19);
        Cantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantidad de Responsabilidades", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        Cantidad.setEnabled(false);
        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });

        codigo1.setMaximumRowCount(32);
        codigo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 01:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo1.setEnabled(false);

        codigo2.setMaximumRowCount(32);
        codigo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 02:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo2.setEnabled(false);

        codigo3.setMaximumRowCount(32);
        codigo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 03:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo3.setEnabled(false);

        codigo4.setMaximumRowCount(32);
        codigo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 04:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo4.setEnabled(false);

        codigo5.setMaximumRowCount(32);
        codigo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 05:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo5.setEnabled(false);

        codigo6.setMaximumRowCount(32);
        codigo6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 06:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo6.setEnabled(false);

        codigo7.setMaximumRowCount(32);
        codigo7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 07:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo7.setEnabled(false);

        codigo8.setMaximumRowCount(32);
        codigo8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 08:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo8.setEnabled(false);

        codigo9.setMaximumRowCount(32);
        codigo9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 09:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo9.setEnabled(false);

        codigo10.setMaximumRowCount(32);
        codigo10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 10:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo10.setEnabled(false);

        codigo13.setMaximumRowCount(32);
        codigo13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 13:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo13.setEnabled(false);

        codigo16.setMaximumRowCount(32);
        codigo16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 16:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo16.setEnabled(false);

        codigo11.setMaximumRowCount(32);
        codigo11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 11:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo11.setEnabled(false);

        codigo14.setMaximumRowCount(32);
        codigo14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 14:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo14.setEnabled(false);

        codigo17.setMaximumRowCount(32);
        codigo17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 17:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo17.setEnabled(false);

        codigo12.setMaximumRowCount(32);
        codigo12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 12:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo12.setEnabled(false);

        codigo15.setMaximumRowCount(32);
        codigo15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 15:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo15.setEnabled(false);

        codigo18.setMaximumRowCount(32);
        codigo18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código 18:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        codigo18.setEnabled(false);

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.setEnabled(false);
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lista Códigos:", "01-  Aporte especial para la administración de justicia", "02-  Gravamen a los movimientos financieros", "03-  Impuesto al patrimonio", "04-  Impuesto de renta y complementario régimen especial", "05-  Impuesto de renta y complementario régimen ordinario", "06-  Ingresos y patrimonio", "07-  Retención en la fuente a título de renta", "08-  Retención timbre nacional", "09-  Retención en la fuente en el impuesto sobre las ventas", "10-  Usuario aduanero", "11-  Ventas régimen común", "12-  Ventas régimen simplificado", "13-  Gran contribuyente", "14-  Informante de exogena", "15-  Autorretenedor", "16-  Obligación a facturar por ingresos bienes y/o servicios excluidos", "17-  Profesionales de compra y venta de divisas", "18-  Precios de transferencia", "19-  Productor de bienes y/o servicios exentos (incluye exportadores)", "20-  Obtención NIT Dto. 3050 de 1997 (Art. 3o)", "21-  Declarar ingreso o salida del país de divisas o moneda legal", "22-  Obligado a declarar a nombre de terceros", "23-  Agente de retención en ventas", "24-  Declaración consolidada precios de transferencia", "25-  Declaración individual precios de transferencia", "26- Derechos de explotación juegos localizados", "27- Derechos de explotación juegos Novedosos", "28- Derechos de explotación juegos Promociónales", "39- Derechos de explotación juegos Rifas", "30- Derechos de explotación juegos gallísticos y caninos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(codigo16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(codigo17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(codigo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(codigo14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(codigo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(codigo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(codigo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(codigo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(codigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(codigo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(codigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Volver, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /* Está función espera que el usuario una de las transacciones del menú desplegable
    que contiene los tipos de transacciones, y almacena en una variable cual tipo
    de transacción es, si no selecciona un tipo de transacción se reinicia la interfaz.
    Apenas se selecciona una transacción se habilita el menú desplegable para 
    seleccionar la cantidad de responsabilidades del usuario y se activa el 
    botón de aceptar*/
    private void TransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaccionActionPerformed
        switch (Transaccion.getSelectedIndex()){
            case 1:
                Tipo="InscripciónRUT";
                jLabel1.setEnabled(true);
                Cantidad.setEnabled(true);
                Cantidad.setSelectedIndex(0);
                codigo1.setEnabled(false);
                codigo2.setEnabled(false);
                codigo3.setEnabled(false);
                codigo4.setEnabled(false);
                codigo5.setEnabled(false);
                codigo6.setEnabled(false);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                Aceptar.setEnabled(true);
                break;
            case 2:
                Tipo="CambioRUT";
                jLabel1.setEnabled(true);
                Cantidad.setEnabled(true);
                Cantidad.setSelectedIndex(0);
                codigo1.setEnabled(false);
                codigo2.setEnabled(false);
                codigo3.setEnabled(false);
                codigo4.setEnabled(false);
                codigo5.setEnabled(false);
                codigo6.setEnabled(false);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                Aceptar.setEnabled(true);
                break;
            default:
                start();
                break;
        }
    }//GEN-LAST:event_TransaccionActionPerformed
    /*De acuerdo a la cantidad de responsabilidades seleccionada habilidad la 
    cantidad de cogidos a ingresar desde 1 hasta 18 códigos de responsabilidades
    tiene una persona*/
    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
        switch (Cantidad.getSelectedIndex()){
            case 1:
                codigo1.setEnabled(true);
                codigo2.setEnabled(false);
                codigo3.setEnabled(false);
                codigo4.setEnabled(false);
                codigo5.setEnabled(false);
                codigo6.setEnabled(false);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 2:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(false);
                codigo4.setEnabled(false);
                codigo5.setEnabled(false);
                codigo6.setEnabled(false);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 3:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(false);
                codigo5.setEnabled(false);
                codigo6.setEnabled(false);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 4:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(false);
                codigo6.setEnabled(false);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 5:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(false);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 6:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 7:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 8:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 9:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 10:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 11:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(true);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 12:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(true);
                codigo12.setEnabled(true);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 13:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(true);
                codigo12.setEnabled(true);
                codigo13.setEnabled(true);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 14:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(true);
                codigo12.setEnabled(true);
                codigo13.setEnabled(true);
                codigo14.setEnabled(true);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 15:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(true);
                codigo12.setEnabled(true);
                codigo13.setEnabled(true);
                codigo14.setEnabled(true);
                codigo15.setEnabled(true);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 16:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(true);
                codigo12.setEnabled(true);
                codigo13.setEnabled(true);
                codigo14.setEnabled(true);
                codigo15.setEnabled(true);
                codigo16.setEnabled(true);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 17:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(true);
                codigo12.setEnabled(true);
                codigo13.setEnabled(true);
                codigo14.setEnabled(true);
                codigo15.setEnabled(true);
                codigo16.setEnabled(true);
                codigo17.setEnabled(true);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            case 18:
                codigo1.setEnabled(true);
                codigo2.setEnabled(true);
                codigo3.setEnabled(true);
                codigo4.setEnabled(true);
                codigo5.setEnabled(true);
                codigo6.setEnabled(true);
                codigo7.setEnabled(true);
                codigo8.setEnabled(true);
                codigo9.setEnabled(true);
                codigo10.setEnabled(true);
                codigo11.setEnabled(true);
                codigo12.setEnabled(true);
                codigo13.setEnabled(true);
                codigo14.setEnabled(true);
                codigo15.setEnabled(true);
                codigo16.setEnabled(true);
                codigo17.setEnabled(true);
                codigo18.setEnabled(true);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
            default:
                codigo1.setEnabled(false);
                codigo2.setEnabled(false);
                codigo3.setEnabled(false);
                codigo4.setEnabled(false);
                codigo5.setEnabled(false);
                codigo6.setEnabled(false);
                codigo7.setEnabled(false);
                codigo8.setEnabled(false);
                codigo9.setEnabled(false);
                codigo10.setEnabled(false);
                codigo11.setEnabled(false);
                codigo12.setEnabled(false);
                codigo13.setEnabled(false);
                codigo14.setEnabled(false);
                codigo15.setEnabled(false);
                codigo16.setEnabled(false);
                codigo17.setEnabled(false);
                codigo18.setEnabled(false);
                codigo1.setSelectedIndex(0);
                codigo2.setSelectedIndex(0);
                codigo3.setSelectedIndex(0);
                codigo4.setSelectedIndex(0);
                codigo5.setSelectedIndex(0);
                codigo6.setSelectedIndex(0);
                codigo7.setSelectedIndex(0);
                codigo8.setSelectedIndex(0);
                codigo9.setSelectedIndex(0);
                codigo10.setSelectedIndex(0);
                codigo11.setSelectedIndex(0);
                codigo12.setSelectedIndex(0);
                codigo13.setSelectedIndex(0);
                codigo14.setSelectedIndex(0);
                codigo15.setSelectedIndex(0);
                codigo16.setSelectedIndex(0);
                codigo17.setSelectedIndex(0);
                codigo18.setSelectedIndex(0);
                break;
        }
    }//GEN-LAST:event_CantidadActionPerformed
    /*al activar este botón se envía la transacción, generando un texto plano con 
    los datos que debe tener una como el ID, Serial del documento. La clase de la 
    transacción como impuestos y el tipo de la transacción que se encuentra almacenada
    en la variable tipo, luego se verifica que se haya seleccionado la cantidad
    de responsabilidades y que todas las responsabilidades tengan su código, donde 
    se toman los códigos de las responsabilidades y se escriben como los datos
    del texto plano que se forma con la transacción. Luego se debe enviar el 
    texto plano (se imprime) y se reinician todos los 
    datos de la app para poder realizar una nueva transacción*/
    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        String tran;
        switch (Cantidad.getSelectedIndex()){
            case 1:
                if (codigo1.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar código");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Código="+codigo1.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 2:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 3:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 4:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()+"-"+codigo4.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 5:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 6:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 7:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 8:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 9:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 10:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 11:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0||codigo11.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex()
                            +"-"+codigo11.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 12:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0||codigo11.getSelectedIndex()==0||codigo12.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex()
                            +"-"+codigo11.getSelectedIndex()+"-"+codigo12.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 13:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0||codigo11.getSelectedIndex()==0||codigo12.getSelectedIndex()==0
                        ||codigo13.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex()
                            +"-"+codigo11.getSelectedIndex()+"-"+codigo12.getSelectedIndex()+"-"+codigo13.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 14:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0||codigo11.getSelectedIndex()==0||codigo12.getSelectedIndex()==0
                        ||codigo13.getSelectedIndex()==0||codigo14.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex()
                            +"-"+codigo11.getSelectedIndex()+"-"+codigo12.getSelectedIndex()+"-"+codigo13.getSelectedIndex()+"-"+codigo14.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 15:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0||codigo11.getSelectedIndex()==0||codigo12.getSelectedIndex()==0
                        ||codigo13.getSelectedIndex()==0||codigo14.getSelectedIndex()==0||codigo15.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex()
                            +"-"+codigo11.getSelectedIndex()+"-"+codigo12.getSelectedIndex()+"-"+codigo13.getSelectedIndex()+"-"+codigo14.getSelectedIndex()+"-"+codigo15.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 16:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0||codigo11.getSelectedIndex()==0||codigo12.getSelectedIndex()==0
                        ||codigo13.getSelectedIndex()==0||codigo14.getSelectedIndex()==0||codigo15.getSelectedIndex()==0
                        ||codigo16.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex()
                            +"-"+codigo11.getSelectedIndex()+"-"+codigo12.getSelectedIndex()+"-"+codigo13.getSelectedIndex()+"-"+codigo14.getSelectedIndex()+"-"+codigo15.getSelectedIndex()+"-"+codigo16.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 17:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0||codigo11.getSelectedIndex()==0||codigo12.getSelectedIndex()==0
                        ||codigo13.getSelectedIndex()==0||codigo14.getSelectedIndex()==0||codigo15.getSelectedIndex()==0
                        ||codigo16.getSelectedIndex()==0||codigo17.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex()
                            +"-"+codigo11.getSelectedIndex()+"-"+codigo12.getSelectedIndex()+"-"+codigo13.getSelectedIndex()+"-"+codigo14.getSelectedIndex()+"-"+codigo15.getSelectedIndex()+"-"+codigo16.getSelectedIndex()+"-"+codigo17.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            case 18:
                if (codigo1.getSelectedIndex()==0||codigo2.getSelectedIndex()==0||codigo3.getSelectedIndex()==0
                        ||codigo4.getSelectedIndex()==0||codigo5.getSelectedIndex()==0||codigo6.getSelectedIndex()==0
                        ||codigo7.getSelectedIndex()==0||codigo8.getSelectedIndex()==0||codigo9.getSelectedIndex()==0
                        ||codigo10.getSelectedIndex()==0||codigo11.getSelectedIndex()==0||codigo12.getSelectedIndex()==0
                        ||codigo13.getSelectedIndex()==0||codigo14.getSelectedIndex()==0||codigo15.getSelectedIndex()==0
                        ||codigo16.getSelectedIndex()==0||codigo17.getSelectedIndex()==0||codigo18.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this,"ERROR seleccionar códigos");
                }
                else{
                    tran= "ID:"+Integer.toString(usuario.ID)+" Serial:"+Integer.toString(usuario.Serial)+" Clase:Impuestos Tipo:"+Tipo+" Datos:Códigos="+codigo1.getSelectedIndex()+"-"+codigo2.getSelectedIndex()+"-"+codigo3.getSelectedIndex()
                            +"-"+codigo4.getSelectedIndex()+"-"+codigo5.getSelectedIndex()+"-"+codigo6.getSelectedIndex()+"-"+codigo7.getSelectedIndex()+"-"+codigo8.getSelectedIndex()+"-"+codigo9.getSelectedIndex()+"-"+codigo10.getSelectedIndex()
                            +"-"+codigo11.getSelectedIndex()+"-"+codigo12.getSelectedIndex()+"-"+codigo13.getSelectedIndex()+"-"+codigo14.getSelectedIndex()+"-"+codigo15.getSelectedIndex()+"-"+codigo16.getSelectedIndex()+"-"+codigo17.getSelectedIndex()
                            +"-"+codigo18.getSelectedIndex();
                    System.out.println("Transacción de "+usuario.Nombre+"\n"+tran);
                    JOptionPane.showMessageDialog(this,"Transacción Enviada");
                    usuario.setVisible(true);
                    this.setVisible(false);
                    usuario.borrar();
                    start();
                }
                break;
            default:
                JOptionPane.showMessageDialog(this,"ERROR seleccionar cantidad de responsabilidades");
                break;
        }
    }//GEN-LAST:event_AceptarActionPerformed
    // Vuelve al menú de clases de transacciones, reiniciando la interfaz y variables de este menú
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        usuario.Abrirmenu();
        start();
    }//GEN-LAST:event_VolverActionPerformed
    // Función para reiniciar la interfaz y variables de la clase luego de salir del menú de impuestos
    public void start(){
        Tipo="";
        Transaccion.setSelectedIndex(0);
        jLabel1.setEnabled(false);
        Cantidad.setEnabled(false);
        Cantidad.setSelectedIndex(0);
        codigo1.setEnabled(false);
        codigo2.setEnabled(false);
        codigo3.setEnabled(false);
        codigo4.setEnabled(false);
        codigo5.setEnabled(false);
        codigo6.setEnabled(false);
        codigo7.setEnabled(false);
        codigo8.setEnabled(false);
        codigo9.setEnabled(false);
        codigo10.setEnabled(false);
        codigo11.setEnabled(false);
        codigo12.setEnabled(false);
        codigo13.setEnabled(false);
        codigo14.setEnabled(false);
        codigo15.setEnabled(false);
        codigo16.setEnabled(false);
        codigo17.setEnabled(false);
        codigo18.setEnabled(false);
        codigo1.setSelectedIndex(0);
        codigo2.setSelectedIndex(0);
        codigo3.setSelectedIndex(0);
        codigo4.setSelectedIndex(0);
        codigo5.setSelectedIndex(0);
        codigo6.setSelectedIndex(0);
        codigo7.setSelectedIndex(0);
        codigo8.setSelectedIndex(0);
        codigo9.setSelectedIndex(0);
        codigo10.setSelectedIndex(0);
        codigo11.setSelectedIndex(0);
        codigo12.setSelectedIndex(0);
        codigo13.setSelectedIndex(0);
        codigo14.setSelectedIndex(0);
        codigo15.setSelectedIndex(0);
        codigo16.setSelectedIndex(0);
        codigo17.setSelectedIndex(0);
        codigo18.setSelectedIndex(0);
        Aceptar.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impuestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JComboBox<String> Cantidad;
    private javax.swing.JComboBox<String> Transaccion;
    private javax.swing.JButton Volver;
    private javax.swing.JComboBox<String> codigo1;
    private javax.swing.JComboBox<String> codigo10;
    private javax.swing.JComboBox<String> codigo11;
    private javax.swing.JComboBox<String> codigo12;
    private javax.swing.JComboBox<String> codigo13;
    private javax.swing.JComboBox<String> codigo14;
    private javax.swing.JComboBox<String> codigo15;
    private javax.swing.JComboBox<String> codigo16;
    private javax.swing.JComboBox<String> codigo17;
    private javax.swing.JComboBox<String> codigo18;
    private javax.swing.JComboBox<String> codigo2;
    private javax.swing.JComboBox<String> codigo3;
    private javax.swing.JComboBox<String> codigo4;
    private javax.swing.JComboBox<String> codigo5;
    private javax.swing.JComboBox<String> codigo6;
    private javax.swing.JComboBox<String> codigo7;
    private javax.swing.JComboBox<String> codigo8;
    private javax.swing.JComboBox<String> codigo9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
